/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class atms_app_my_application_c_JNI */

#ifndef _Included_atms_app_my_application_c_JNI
#define _Included_atms_app_my_application_c_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     atms_app_my_application_c_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_atms_app_agiskclient_JNI_add
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     atms_app_my_application_c_JNI
 * Method:    checkPasswd
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_atms_app_agiskclient_JNI_checkPasswd
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
